export const CHAR_TYPES = {
  LOAD_CHARS:"LOAD_CHARS",
  ADD_CHAR_TO_LIST: "ADD_CHAR_TO_LIST",
  REMOVE_CHAR_FROM_LIST: "REMOVE_CHAR_FROM_LIST",
  REMOVE_ALL_CHARS: "REMOVE_ALL_CHARS",
  CLEAR_CART: "CLEAR_CART"
  
};
